export const POKE_TYPES = [
  { name: "normal", color: "#A8A77A" },
  { name: "fighting", color: "#C22E28" },
  { name: "flying", color: "#A98FF3" },
  { name: "poison", color: "#A33EA1" },
  { name: "ground", color: "#E2BF65" },
  { name: "rock", color: "#B6A136" },
  { name: "bug", color: "#A6B91A" },
  { name: "ghost", color: "#735797" },
  { name: "steel", color: "#B7B7CE" },
  { name: "fire", color: "#EE8130" },
  { name: "water", color: "#6390F0" },
  { name: "grass", color: "#7AC74C" },
  { name: "electric", color: "#6FBCF0" },
  { name: "psychic", color: "#F95587" },
  { name: "ice", color: "#96D9D6" },
  { name: "dragon", color: "#6F35FC" },
  { name: "dark", color: "#705746" },
  { name: "fairy", color: "#D685AD" },
];
